---
- name: Install Outline
  hosts: all
  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: common, tags: ["common"] }
    - { role: node, tags: ["node"] }
    - { role: redis, tags: ["redis"] }
    - { role: outline, tags: ["outline"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: certbot, tags: ["certbot"] }
