---
- name: Install Certbot repository
  shell: "amazon-linux-extras install epel -y"
  become: true

- name: Install Certbot
  yum:
    name:
      - certbot
      - certbot-nginx
    state: present
    update_cache: yes
  become: true

- name: Get Let's Encrypt Certificate
  shell: "certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos -m {{ admin_email }}"
  become: true
